### ISSUE TITLE
Unable to create new project using Composer 2.0.0-RC1

### ISSUE THREAD

**Issue by ADmad** [bolt/project#32] opened 2020-09-27 16:12 UTC
```
$ composer create-project bolt/project bolt4
Creating a "bolt/project" project at "./bolt4"
Installing bolt/project (1.2.1)
  - Downloading bolt/project (1.2.1)
  - Installing bolt/project (1.2.1): Extracting archive
Created project in /srv/sites/bolt4
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - drupol/composer-packages is locked to version 1.1.2 and an update of this package was not requested.
    - drupol/composer-packages 1.1.2 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - drupol/composer-packages 1.1.2 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - bolt/core 4.0.0 requires drupol/composer-packages ^1.1 -> satisfiable by drupol/composer-packages[1.1.2].
    - bolt/core is locked to version 4.0.0 and an update of this package was not requested.

Use the option --with-all-dependencies to allow upgrades, downgrades and removals for packages currently locked to specific versions.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
```

**Comment by bobdenotter** [comment] 2020-09-27 20:44
Duplicate of https://github.com/bolt/core/issues/1492

**Closed by bobdenotter** 2020-09-27 20:44 UTC
